import { wgslVitePlugin } from "@vgpu/wgsl/loader-vite";
import { defineConfig } from "vite";

export default defineConfig({
  // data/build/ is generated by `npm run build:data` and gitignored; serving
  // it as publicDir makes terrain.json/heights/satellite reachable at the
  // site root in dev and copied verbatim into dist/ on build. The debug-only
  // debug-alignment.png is removed from dist/ by scripts/prune-dist.mjs
  // (runs at the end of `npm run build`).
  publicDir: "data/build",
  plugins: [wgslVitePlugin()],
});
